config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  get '/appointments/doc_notes'
  get '/appointments/doc_notes_list'
  get '/appointments/doc_search'
  get '/appointments/patient_app'
  get '/appointments/app_check'
  get '/appointments/app_delete'
  get '/appointments/app_delete_final'
  get '/homepage/future_feature'

  resources :invoices

  resources :invoice_statuses

  resources :diag_codes

  resources :physicians

  resources :patients

  resources :app_statuses

  resources :apps

  resources :appointments

  root 'homepage#index'

  get '/appointments/doc_notes'

end

app/models/diag_code.rb
class DiagCode < ActiveRecord::Base

  has_many :appointments

  def code_value
    "#{diag_code}"
  end

end

app/controllers/diag_codes_controller.rb
class DiagCodesController < ApplicationController
  before_action :set_diag_code, only: [:show, :edit, :update, :destroy]

  # GET /diag_codes
  # GET /diag_codes.json
  def index
    @diag_codes = DiagCode.all
  end

  # GET /diag_codes/1
  # GET /diag_codes/1.json
  def show
  end

  # GET /diag_codes/new
  def new
    @diag_code = DiagCode.new
  end

  # GET /diag_codes/1/edit
  def edit
  end

  # POST /diag_codes
  # POST /diag_codes.json
  def create
    @diag_code = DiagCode.new(diag_code_params)

    respond_to do |format|
      if @diag_code.save
        format.html { redirect_to @diag_code, notice: 'Diag code was successfully created.' }
        format.json { render :show, status: :created, location: @diag_code }
      else
        format.html { render :new }
        format.json { render json: @diag_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diag_codes/1
  # PATCH/PUT /diag_codes/1.json
  def update
    respond_to do |format|
      if @diag_code.update(diag_code_params)
        format.html { redirect_to @diag_code, notice: 'Diag code was successfully updated.' }
        format.json { render :show, status: :ok, location: @diag_code }
      else
        format.html { render :edit }
        format.json { render json: @diag_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diag_codes/1
  # DELETE /diag_codes/1.json
  def destroy
    @diag_code.destroy
    respond_to do |format|
      format.html { redirect_to diag_codes_url, notice: 'Diag code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diag_code
      @diag_code = DiagCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diag_code_params
      params.require(:diag_code).permit(:diag_code, :description)
    end
end

app/helpers/diag_codes_helper.rb
module DiagCodesHelper
end

app/views/diag_codes/_form.html.erb
<%= form_for @diag_code, :html => { :class => "form-horizontal diag_code" } do |f| %>

    <% if @diag_code.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@diag_code.errors.count, "error") %> prohibited this diag_code from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @diag_code.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :diag_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :diag_code, :class => 'form-control' %>
    </div>
    <%= error_span(@diag_code[:diag_code]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@diag_code[:description]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            diag_codes_path, :class => 'btn btn-default' %>

<% end %>

app/views/diag_codes/edit.html.erb
<%- model_class = DiagCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diag_codes/index.html.erb
<%- model_class = DiagCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:diag_code) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @diag_codes.each do |diag_code| %>
      <tr>
        <td><%= link_to diag_code.id, diag_code_path(diag_code) %></td>
        <td><%= diag_code.diag_code %></td>
        <td><%= diag_code.description %></td>
        <td><%=l diag_code.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_diag_code_path(diag_code), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      diag_code_path(diag_code),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_diag_code_path,
            :class => 'btn btn-primary' %>

app/views/diag_codes/new.html.erb
<%- model_class = DiagCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diag_codes/show.html.erb
<%- model_class = DiagCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:diag_code) %>:</strong></dt>
  <dd><%= @diag_code.diag_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @diag_code.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              diag_codes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_diag_code_path(@diag_code), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              diag_code_path(@diag_code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>