config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  get '/appointments/doc_notes'
  get '/appointments/doc_notes_list'
  get '/appointments/doc_search'
  get '/appointments/patient_app'
  get '/appointments/app_check'
  get '/appointments/app_delete'
  get '/appointments/app_delete_final'
  get '/homepage/future_feature'

  resources :invoices

  resources :invoice_statuses

  resources :diag_codes

  resources :physicians

  resources :patients

  resources :app_statuses

  resources :apps

  resources :appointments

  root 'homepage#index'

  get '/appointments/doc_notes'

end

app/models/app_status.rb
class AppStatus < ActiveRecord::Base

  has_many :appointments
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :app_status
  belongs_to :patient
  belongs_to :physician
  belongs_to :diag_code
  has_one :invoice

  scope :physician, -> (physician_id) { where physician_id: physician_id }
  scope :patient, -> (patient_id) { where patient_id: patient_id }

  def app_info
    "#{app_date}:  #{patient.last_name}, #{patient.first_name}"
  end

end

app/models/diag_code.rb
class DiagCode < ActiveRecord::Base

  has_many :appointments

  def code_value
    "#{diag_code}"
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  belongs_to :invoice_status
  belongs_to :appointment
end

app/models/invoice_status.rb
class InvoiceStatus < ActiveRecord::Base
  has_many :invoices
end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments

  #method for lastname, firstname
  def full_name
    "#{last_name}, #{first_name}"
  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments

  #method for lastname, firstname

  def full_name
    "Dr. #{first_name} #{last_name}"
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end

  def future_feature
  end
end

app/controllers/invoice_statuses_controller.rb
class InvoiceStatusesController < ApplicationController
  before_action :set_invoice_status, only: [:show, :edit, :update, :destroy]

  # GET /invoice_statuses
  # GET /invoice_statuses.json
  def index
    @invoice_statuses = InvoiceStatus.all
  end

  # GET /invoice_statuses/1
  # GET /invoice_statuses/1.json
  def show
  end

  # GET /invoice_statuses/new
  def new
    @invoice_status = InvoiceStatus.new
  end

  # GET /invoice_statuses/1/edit
  def edit
  end

  # POST /invoice_statuses
  # POST /invoice_statuses.json
  def create
    @invoice_status = InvoiceStatus.new(invoice_status_params)

    respond_to do |format|
      if @invoice_status.save
        format.html { redirect_to @invoice_status, notice: 'Invoice status was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_status }
      else
        format.html { render :new }
        format.json { render json: @invoice_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_statuses/1
  # PATCH/PUT /invoice_statuses/1.json
  def update
    respond_to do |format|
      if @invoice_status.update(invoice_status_params)
        format.html { redirect_to @invoice_status, notice: 'Invoice status was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_status }
      else
        format.html { render :edit }
        format.json { render json: @invoice_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_statuses/1
  # DELETE /invoice_statuses/1.json
  def destroy
    @invoice_status.destroy
    respond_to do |format|
      format.html { redirect_to invoice_statuses_url, notice: 'Invoice status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_status
      @invoice_status = InvoiceStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_status_params
      params.require(:invoice_status).permit(:status_name)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:appointment_id, :amount, :invoice_status_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]


  def patient_search
    @patients = Patient.all
    @patient_id = params[:id]
    @appointments = Appointment.all
    @physicians = Physician.all
  end

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:last_name, :first_name, :phone, :email)
    end
end

app/helpers/app_statuses_helper.rb
module AppStatusesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/diag_codes_helper.rb
module DiagCodesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/invoice_statuses_helper.rb
module InvoiceStatusesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/invoice_statuses/_form.html.erb
<%= form_for @invoice_status, :html => { :class => "form-horizontal invoice_status" } do |f| %>

    <% if @invoice_status.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@invoice_status.errors.count, "error") %> prohibited this invoice_status from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @invoice_status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :status_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status_name, :class => 'form-control' %>
    </div>
    <%= error_span(@invoice_status[:status_name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            invoice_statuses_path, :class => 'btn btn-default' %>

<% end %>

app/views/invoice_statuses/edit.html.erb
<%- model_class = InvoiceStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/invoice_statuses/index.html.erb
<%- model_class = InvoiceStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:status_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @invoice_statuses.each do |invoice_status| %>
      <tr>
        <td><%= link_to invoice_status.id, invoice_status_path(invoice_status) %></td>
        <td><%= invoice_status.status_name %></td>
        <td><%=l invoice_status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_invoice_status_path(invoice_status), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      invoice_status_path(invoice_status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_invoice_status_path,
            :class => 'btn btn-primary' %>

app/views/invoice_statuses/new.html.erb
<%- model_class = InvoiceStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/invoice_statuses/show.html.erb
<%- model_class = InvoiceStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:status_name) %>:</strong></dt>
  <dd><%= @invoice_status.status_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              invoice_statuses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_invoice_status_path(@invoice_status), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              invoice_status_path(@invoice_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>