config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  get '/appointments/doc_notes'
  get '/appointments/doc_notes_list'
  get '/appointments/doc_search'
  get '/appointments/patient_app'
  get '/appointments/app_check'
  get '/appointments/app_delete'
  get '/appointments/app_delete_final'
  get '/homepage/future_feature'

  resources :invoices

  resources :invoice_statuses

  resources :diag_codes

  resources :physicians

  resources :patients

  resources :app_statuses

  resources :apps

  resources :appointments

  root 'homepage#index'

  get '/appointments/doc_notes'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :app_status
  belongs_to :patient
  belongs_to :physician
  belongs_to :diag_code
  has_one :invoice

  scope :physician, -> (physician_id) { where physician_id: physician_id }
  scope :patient, -> (patient_id) { where patient_id: patient_id }

  def app_info
    "#{app_date}:  #{patient.last_name}, #{patient.first_name}"
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def doc_notes
    @appointments = Appointment.all
    @physicians = Physician.all
  end

  def doc_notes_list
    @appointments = Appointment.where(nil)
    @appointments = @appointments.physician(params[:physician_id]) if params[:physician_id].present?
  end

  def doc_search
    @appointments = Appointment.all
    @physicians = Physician.all
  end

  def patient_app
    @appointment = Appointment.new
  end

  def app_check
    @appointments = Appointment.all
    @patients = Patient.all
  end

  def app_delete
    @appointments = Appointment.where(nil)
    @appointments = @appointments.patient(params[:patient_id]) if params[:patient_id].present?
  end

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:patient_id, :physician_id, :app_date, :reason, :dr_notes, :app_status_id, :diag_code_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment, :html => { :class => "form-horizontal appointment" } do |f| %>

    <% if @appointment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @appointment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :patient_id, :class => 'control-label' %>

    <div class="controls">
      <%= f.collection_select :patient_id, Patient.all, :id, :full_name %>
    </div>
    <%= error_span(@appointment[:patient_id]) %>
  </div>

  <div class="control-group">
    <%= f.label :physician_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :physician_id, Physician.all, :id, :full_name %>
    </div>
    <%= error_span(@appointment[:physician_id]) %>
  </div>

    <div class="control-group">
      <%= f.label :app_date, :class => 'control-label'  %>
      <div class="input-group date" id="datetimepicker">
        <%= f.text_field :app_date, class: 'form-control'%>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>

  <div class="control-group">
    <%= f.label "Reason for Appointment", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :reason, :class => 'form-control' %>
    </div>
    <%= error_span(@appointment[:reason]) %>
  </div>

  <div class="control-group">
    <%= f.label "Doctor's Notes", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :dr_notes, :class => 'form-control' %>
    </div>
    <%= error_span(@appointment[:dr_notes]) %>
  </div>

  <div class="control-group">
    <%= f.label :app_status_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :app_status_id, AppStatus.all, :id, :status %>
    </div>
    <%= error_span(@appointment[:app_status_id]) %>
  </div>

  <div class="control-group">
    <%= f.label :diag_code_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :diag_code_id, DiagCode.all, :id, :diag_code %>
    </div>
    <%= error_span(@appointment[:diag_code_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            appointments_path, :class => 'btn btn-default' %>

<% end %>
</div>

app/views/appointments/app_check.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1>Check Appointment</h1>
  <h3>Select a Patient</h3>
</div>



<table class="table table-striped">
  <thead>
  <tr>
    <th>Patient</th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.full_name %></td>
        <td>
          <%= link_to 'Select', appointments_app_delete_path(patient_id: patient) %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/appointments/app_delete.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <h4>Select the Appointment to delete</h4>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:patient_id) %></th>
    <th><%= model_class.human_attribute_name(:physician_id) %></th>
    <th><%= model_class.human_attribute_name(:app_date) %></th>
    <th><%= model_class.human_attribute_name(:reason) %></th>

    <th><%= model_class.human_attribute_name(:app_status_id) %></th>

    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.full_name %></td>
        <td><%= appointment.physician.full_name %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.reason %></td>

        <td><%= appointment.app_status.status %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_appointment_path(appointment), :class => 'btn btn-default btn-xs' %>

        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/appointments/doc_notes.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1>Update Doctor's Notes</h1>
  <h3>Select a Physician</h3>
</div>



<table class="table table-striped">
  <thead>
  <tr>
    <th>Doctor</th>
    <th><%= model_class.human_attribute_name(:phone) %></th>
    <th><%= model_class.human_attribute_name(:email) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.full_name %></td>
        <td><%= physician.phone %></td>
        <td><%= physician.email %></td>
        <td>
          <%= link_to 'Select', appointments_doc_notes_list_path(physician_id: physician) %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>



app/views/appointments/doc_notes_list.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <h4>Select the Appointment to Add Notes or Diagnostic Code</h4>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:patient_id) %></th>
    <th><%= model_class.human_attribute_name(:physician_id) %></th>
    <th><%= model_class.human_attribute_name(:app_date) %></th>
    <th><%= model_class.human_attribute_name(:reason) %></th>
    <th><%= model_class.human_attribute_name(:dr_notes) %></th>
    <th><%= model_class.human_attribute_name(:app_status_id) %></th>
    <th><%= model_class.human_attribute_name(:diag_code_id) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.full_name %></td>
        <td><%= appointment.physician.full_name %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.dr_notes %></td>
        <td><%= appointment.app_status.status %></td>
        <td><%= appointment.diag_code_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_appointment_path(appointment), :class => 'btn btn-default btn-xs' %>

        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/appointments/doc_search.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1>Appointment Booking</h1>
  <h3>Select a Physician</h3>
</div>



<table class="table table-striped">
  <thead>
  <tr>
    <th>Doctor</th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.full_name %></td>
        <td>
          <%= link_to 'Select', appointments_doc_notes_list_path(physician_id: physician) %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/appointments/edit.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/appointments/index.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:patient_id) %></th>
      <th><%= model_class.human_attribute_name(:physician_id) %></th>
      <th><%= model_class.human_attribute_name(:app_date) %></th>
      <th><%= model_class.human_attribute_name(:reason) %></th>
      <th><%= model_class.human_attribute_name(:dr_notes) %></th>
      <th><%= model_class.human_attribute_name(:app_status_id) %></th>
      <th><%= model_class.human_attribute_name(:diag_code_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= link_to appointment.id, appointment_path(appointment) %></td>
        <td><%= appointment.patient.full_name %></td>
        <td><%= appointment.physician.full_name %></td>
        <td><%= appointment.app_date %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.dr_notes %></td>
        <td><%= appointment.app_status.status %></td>
        <td><%= appointment.diag_code_id %></td>
        <td><%= appointment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_appointment_path(appointment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      appointment_path(appointment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_appointment_path,
            :class => 'btn btn-primary' %>

app/views/appointments/new.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/appointments/patient_app.erb
<%= form_for @appointment, :html => { :class => "form-horizontal appointment" } do |f| %>

    <% if @appointment.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @appointment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :patient_id, :class => 'control-label' %>

      <div class="controls">
        <%= f.collection_select :patient_id, Patient.all, :id, :full_name %>
      </div>
      <%= error_span(@appointment[:patient_id]) %>
    </div>

    <div class="control-group">
      <%= f.label :physician_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :physician_id, Physician.all, :id, :full_name %>
      </div>
      <%= error_span(@appointment[:physician_id]) %>
    </div>

    <div class="control-group">
      <%= f.label :app_date, :class => 'control-label'  %>
      <div class="input-group date" id="datetimepicker">
        <%= f.text_field :app_date, class: 'form-control'%>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>

      <div class="control-group">
        <%= f.label "Reason for Appointment", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :reason, :class => 'form-control' %>
        </div>
        <%= error_span(@appointment[:reason]) %>
      </div>

      <div class="hidden">
        <%= f.label :app_status_id, :class => 'control-label' %>
        <div class="controls">
          <%= f.collection_select :app_status_id, AppStatus.all, :id, :status %>
        </div>
        <%= error_span(@appointment[:app_status_id]) %>
      </div>




      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  appointments_path, :class => 'btn btn-default' %>

<% end %>
</div>

app/views/appointments/show.html.erb
<%- model_class = Appointment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:patient_id) %>:</strong></dt>
  <dd><%= @appointment.patient.full_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:physician_id) %>:</strong></dt>
  <dd><%= @appointment.physician.full_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:app_date) %>:</strong></dt>
  <dd><%= @appointment.app_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reason) %>:</strong></dt>
  <dd><%= @appointment.reason %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dr_notes) %>:</strong></dt>
  <dd><%= @appointment.dr_notes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:app_status_id) %>:</strong></dt>
  <dd><%= @appointment.app_status.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diag_code_id) %>:</strong></dt>
  <dd><%= @appointment.diag_code_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              appointments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_appointment_path(@appointment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              appointment_path(@appointment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>