config/routes.rb
Rails.application.routes.draw do

  get 'homepage/index'
  get '/appointments/doc_notes'
  get '/appointments/doc_notes_list'
  get '/appointments/doc_search'
  get '/appointments/patient_app'
  get '/appointments/app_check'
  get '/appointments/app_delete'
  get '/appointments/app_delete_final'
  get '/homepage/future_feature'

  resources :invoices

  resources :invoice_statuses

  resources :diag_codes

  resources :physicians

  resources :patients

  resources :app_statuses

  resources :apps

  resources :appointments

  root 'homepage#index'

  get '/appointments/doc_notes'

end

app/models/app_status.rb
class AppStatus < ActiveRecord::Base

  has_many :appointments
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :app_status
  belongs_to :patient
  belongs_to :physician
  belongs_to :diag_code
  has_one :invoice

  scope :physician, -> (physician_id) { where physician_id: physician_id }
  scope :patient, -> (patient_id) { where patient_id: patient_id }

  def app_info
    "#{app_date}:  #{patient.last_name}, #{patient.first_name}"
  end

end

app/models/diag_code.rb
class DiagCode < ActiveRecord::Base

  has_many :appointments

  def code_value
    "#{diag_code}"
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  belongs_to :invoice_status
  belongs_to :appointment
end

app/models/invoice_status.rb
class InvoiceStatus < ActiveRecord::Base
  has_many :invoices
end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments

  #method for lastname, firstname
  def full_name
    "#{last_name}, #{first_name}"
  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments

  #method for lastname, firstname

  def full_name
    "Dr. #{first_name} #{last_name}"
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end

  def future_feature
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:appointment_id, :amount, :invoice_status_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]


  def patient_search
    @patients = Patient.all
    @patient_id = params[:id]
    @appointments = Appointment.all
    @physicians = Physician.all
  end

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:last_name, :first_name, :phone, :email)
    end
end

app/helpers/app_statuses_helper.rb
module AppStatusesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/diag_codes_helper.rb
module DiagCodesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ABC Dermatology</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Patients<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Make Appointment', appointments_patient_app_path %></li>
            <li><%= link_to 'Check Appointment', appointments_app_check_path %></li>
            <li><%= link_to 'Register Patient', new_patient_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Invoicing <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Generate Invoice', invoices_path %></li>
            <li><%= link_to 'Physicians', physicians_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Menu<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Physicians', physicians_path %></li>
            <li><%= link_to 'Patients', patients_path %></li>
            <li><%= link_to 'Appointments', appointments_path %></li>
            <li><%= link_to 'Diagnostic Codes', diag_codes_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Reports', homepage_future_feature_path %></li>
          </ul>
        </li>

        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Doctor Menu<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Appointment Update', appointments_doc_notes_path %></li>
        </ul>
        </li>

        <li><%= link_to 'Help', "/resources/patient_help.docx"%></li>


      </ul>

    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>